
[package]
name = "worker"
version = "1.0.0"
edition = "2021"
authors = ["Sher <IRAN's Girl>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.8.5"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
getrandom = { version = "0.2", features = ["js"] }
base64 = "0.22"
hex = "0.4"
hmac = "0.12"
sha2 = "0.10"

[profile.release]
panic = "abort"
lto = true
opt-level = "s"
codegen-units = 1